### ISSUE TITLE
Remove FTP access and change the password for FTP

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/my_webapp_ynh#14]
Hi
I want to know, how can I remove the FTP access for a webapp(the option for having a FTP or not while installation of webapp would be great, just like it asks for database) ?

I would also like to change the password for the FTP of a webapp. Is it possible to change it?

**Comment by steveowashere** [comment]
You can just remove (or comment out) the entries from /etc/ssh/sshd_config when you're done and then restart the ssh service. 

As for the password, if you never want to access it again, just remove the webapp1 user, or change the password like you would for any other user.

**Comment by anmol26s** [comment]
Can't the ssh access be given to the webapp1 to change the password?

**Comment by tituspijean** [comment]
Things have changed since 4 years ago, now we ask wether you want SFTP access or not. Anyway, here is a way to currently remove access:

`yunohost app setting my_webapp with_sftp -v 0`
Re-run the upgrade: `yunohost app upgrade my_webapp --force`
Remove my_webapp from the `sftp.app` group: `deluser my_webapp sftp.app`

To change SFTP password, change user password: `chpasswd <<< "my_webapp:${password}"`
